FROM node:20-alpine AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN corepack enable \
    && corepack prepare pnpm@10.33.0 --activate \
    && pnpm install --frozen-lockfile

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_APP_BASE_URL
ARG VITE_APP_ENV
ARG VITE_AUTH_INVITE_ONLY
ARG VITE_AUTH_ALLOW_SELF_SIGNUP
ARG VITE_AUTH_ALLOW_MAGIC_LINK

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_APP_BASE_URL=$VITE_APP_BASE_URL
ENV VITE_APP_ENV=$VITE_APP_ENV
ENV VITE_AUTH_INVITE_ONLY=$VITE_AUTH_INVITE_ONLY
ENV VITE_AUTH_ALLOW_SELF_SIGNUP=$VITE_AUTH_ALLOW_SELF_SIGNUP
ENV VITE_AUTH_ALLOW_MAGIC_LINK=$VITE_AUTH_ALLOW_MAGIC_LINK

RUN pnpm build

FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD wget -q -O /dev/null http://127.0.0.1/healthz || exit 1
